# Generated by Django 3.2.8 on 2022-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=15)),
                ('descripcion', models.TextField(max_length=100)),
                ('stock', models.IntegerField(max_length=10)),
                ('fechaven', models.DateField()),
                ('preciocompra', models.IntegerField(max_length=10)),
                ('precioventa', models.IntegerField(max_length=10)),
            ],
        ),
    ]
