# Generated by Django 3.2.8 on 2022-05-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30, verbose_name='título')),
                ('tipotrabajo', models.CharField(max_length=30, null=True, verbose_name='tipo de trabajo')),
                ('descripcion', models.TextField(max_length=100, verbose_name='descripción del trabajo')),
                ('imagensol', models.ImageField(upload_to='imagenes/', verbose_name='imagen')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre solicitante')),
                ('celular', models.CharField(max_length=12, verbose_name='celular')),
                ('correo', models.EmailField(max_length=30, verbose_name='correo')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fechaven',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=15, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preciocompra',
            field=models.IntegerField(verbose_name='precio compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioventa',
            field=models.IntegerField(verbose_name='precio venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name='stock'),
        ),
    ]
