# Generated by Django 3.2.8 on 2022-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0002_auto_20220516_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='preciocompra',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=15, null=True, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechavenc',
            field=models.DateField(blank=True, null=True, verbose_name='fecha vencimiento'),
        ),
    ]
